// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// returnAnnotation
Rcpp::DataFrame returnAnnotation(Rcpp::DataFrame dfclique, Rcpp::DataFrame dfaddlist, int topmassf, int topmasstotal, int sizeanG, double tol, double filter, double emptyS);
RcppExport SEXP _CliqueMS_returnAnnotation(SEXP dfcliqueSEXP, SEXP dfaddlistSEXP, SEXP topmassfSEXP, SEXP topmasstotalSEXP, SEXP sizeanGSEXP, SEXP tolSEXP, SEXP filterSEXP, SEXP emptySSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dfclique(dfcliqueSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dfaddlist(dfaddlistSEXP);
    Rcpp::traits::input_parameter< int >::type topmassf(topmassfSEXP);
    Rcpp::traits::input_parameter< int >::type topmasstotal(topmasstotalSEXP);
    Rcpp::traits::input_parameter< int >::type sizeanG(sizeanGSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< double >::type emptyS(emptySSEXP);
    rcpp_result_gen = Rcpp::wrap(returnAnnotation(dfclique, dfaddlist, topmassf, topmasstotal, sizeanG, tol, filter, emptyS));
    return rcpp_result_gen;
END_RCPP
}
// returnCliques
Rcpp::DataFrame returnCliques(Rcpp::DataFrame netdf);
RcppExport SEXP _CliqueMS_returnCliques(SEXP netdfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type netdf(netdfSEXP);
    rcpp_result_gen = Rcpp::wrap(returnCliques(netdf));
    return rcpp_result_gen;
END_RCPP
}
// returnIsotopes
Rcpp::DataFrame returnIsotopes(Rcpp::DataFrame dfclique, int maxCharge, double ppm, double isom);
RcppExport SEXP _CliqueMS_returnIsotopes(SEXP dfcliqueSEXP, SEXP maxChargeSEXP, SEXP ppmSEXP, SEXP isomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dfclique(dfcliqueSEXP);
    Rcpp::traits::input_parameter< int >::type maxCharge(maxChargeSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type isom(isomSEXP);
    rcpp_result_gen = Rcpp::wrap(returnIsotopes(dfclique, maxCharge, ppm, isom));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CliqueMS_returnAnnotation", (DL_FUNC) &_CliqueMS_returnAnnotation, 8},
    {"_CliqueMS_returnCliques", (DL_FUNC) &_CliqueMS_returnCliques, 1},
    {"_CliqueMS_returnIsotopes", (DL_FUNC) &_CliqueMS_returnIsotopes, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CliqueMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
