# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

returnAnnotation <- function(dfclique, dfaddlist, topmassf = 1L, topmasstotal = 10L, sizeanG = 20L, tol = 0.00001, filter = 0.0001, emptyS = -6, normalizeScore = TRUE) {
    .Call(`_cliqueMS_returnAnnotation`, dfclique, dfaddlist, topmassf, topmasstotal, sizeanG, tol, filter, emptyS, normalizeScore)
}

returnCliques <- function(netdf, tol = 0.000001, silent = FALSE) {
    .Call(`_cliqueMS_returnCliques`, netdf, tol, silent)
}

returnIsotopes <- function(dfclique, maxCharge, ppm, isom = 1.003355) {
    .Call(`_cliqueMS_returnIsotopes`, dfclique, maxCharge, ppm, isom)
}

