# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

returnAnnotation <- function(dfclique, dfaddlist, topmassf = 1L, topmasstotal = 10L, sizeanG = 20L, tol = 0.00001, filter = 0.0001, emptyS = 0.000001) {
    .Call(`_CliqueMS_returnAnnotation`, dfclique, dfaddlist, topmassf, topmasstotal, sizeanG, tol, filter, emptyS)
}

returnCliques <- function(netdf) {
    .Call(`_CliqueMS_returnCliques`, netdf)
}

returnIsotopes <- function(dfclique, maxCharge, ppm, isom = 1.003355) {
    .Call(`_CliqueMS_returnIsotopes`, dfclique, maxCharge, ppm, isom)
}

